### PR TITLE
CakePHP 5 upgrade

### PR DESCRIPTION
**Pull request by robertpustulka**
An attempt to make this plugin compatible with CakePHP 5

### CODE REVIEW

**Comment by robertpustulka** [comment]
@josegonzalez Could you take a look?

**Comment by robertpustulka** [comment]
Or @jeremyharris maybe? :)

**Comment by jeremyharris** [comment]
@robertpustulka I haven't used library this in a very long time; none of the current cake projects I'm working with are even upgraded to 5 :/ I don't really qualify as a maintainer anymore, but I'll try.

It looks like travis isn't relevant to the project anymore so we should probably use GH actions for CI so we can see that everything is working ok. When I can see the matrix of tests passing I'll be pretty confident to merge this.

Anyway sorry for the delay. I'll be able to look at this and work on GH actions early next week though :)

**Comment by jeremyharris** [comment]
Hey @robertpustulka I went ahead and added a GH CI workflow and all the tests pass on the versions you specified in the travis yml so I'm merging this and I'll tag a release so you can get back to using the lib :) Thanks for all the work!

**Comment by robertpustulka** [comment]
Thanks a lot!

**Comment by josegonzalez** [comment]
Happy to donate/move this project to friendsofcake if there is significant usage/someone there wants to take over ownership :)

**Pull request merged**
