### PR TITLE
Added support for custom and composite foreign keys.

### PR DESCRIPTION
**Pull request by robertpustulka**
Making the plugin more flexible: part one :)

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add a test for this case?

**Comment by robertpustulka** [comment]
@josegonzalez 
I've megred PR #15 as testing this new feature makes no sense without that fix :)

I've included tests for composite keys handling which also cover that trait fix from #15.

Also found a bug I introduced some time ago, where version_id would never be set in an entity if this field wasn't versioned. It's fixed and assertion has been added for it.

**Comment by robertpustulka** [comment]
Is there anything more to do, could it be merged?

**Comment by josegonzalez** [comment]
Most of the new code isn't covered, so if you want this merged, you're going to need to give me coverage on that.

**Comment by josegonzalez** [comment]
Fuck it, if someone wants this feature and its broken, they can write the docs and fix tests.

**Pull request merged**
