### PR TITLE
Cakephp 4.x

### PR DESCRIPTION
**Pull request by TheMiller2015**
Hello,

since I'm using this plugin in one of my 3.x cake-apps and I had to upgrade, I thought of upgrading this plugin also. 

As of my tests (manual website-tests) and your initial unit tests, this plugin is working pretty fine. Even with the footprint-plugin and the cakephp-authentication plugin. But regarding this, the README has to be updated since the syntax is slightly different. I forgot to update the README.

I hope, everything is fine.

### CODE REVIEW

**Comment by TheMiller2015** [comment]
I don't know why the travis jobs are failing. Locally there is no problem. @josegonzalez can you help merging? I have no idea. Thanks.

**Comment by josegonzalez** [comment]
The `bootstrap.php` file is out of date, and you need to drop all the unsupported PHP versions from the travis.yml.

**Comment by TheMiller2015** [comment]
Thanks for your comment. I don't know if just dropping the unsupported php versions is enough. Maybe we can copy the travis.yml from  FriendsOfCake/cakephp-upload? If not, dropping is not that problem, I could do that. But I don't know how bootstrap.php must look like. Can you tell me or correct the file yourself?

**Comment by josegonzalez** [comment]
Copying the file probably will work. 

I don't have time to work on this for free at the moment, so I'd suggest looking at a working plugin's bootstrap.php and copying that as well?

**Comment by TheMiller2015** [comment]
fi - nal - ly ;) Would you be so kind to merge this pull request. CodeSniffer was pretty strict. But feels good to contribute. Hope I was doing well....

**Comment by josegonzalez** [comment]
Released as 4.0.0.

**Pull request merged**
